# Generated by Django 4.2.3 on 2023-07-19 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Poll",
            new_name="Room",
        ),
    ]
